### ISSUE TITLE
Add metric `PMAD`

### ISSUE THREAD

**Issue by alex-hse-repository** [tinkoff-ai/etna#1014] opened 2022-11-25 14:41 UTC
### 🚀 Feature Request

Add metric class to calculate [PMAD](https://alexanderdyakonov.files.wordpress.com/2018/10/book_08_metrics_12_blog1.pdf) (see page 15)

### Proposal

1. In `functional_metrics.py` create method `pmad` to calculate the metric
2. In `metrics.py` create class `PMAD(Metric)`
3. Define `greater_is_better` property for this metric

### Test cases

1. Add `pmad` function to all the tests in `test_functional_metrics.py`
2. Add `PMAD` class to all the tests in `test_metrics.py`

**Comment by GooseIt** [comment] 2023-02-05 11:16
The reference in commit is accidental, the commit itself shouldn't be reviewed.

**Comment by GooseIt** [comment] 2023-02-05 11:19
As seen [here](https://www.jedox.com/en/blog/error-metrics-how-to-evaluate-forecasts/) and in etna.metrics.functional_metrics.py, WAPE follows the same formula as PMAD, but is more widespread.
Should the issue thereby be closed, or should PMAD be implemented (regardless of the fact that it is a duplicate of WAPE)?

**Comment by Mr-Geekman** [comment] 2023-04-18 14:25
Not relevant because of present `WAPE`.

**Closed by Mr-Geekman** 2023-04-18 14:25 UTC
Labels: enhancement, DKO
